pipeline:
  name: Build poc
  identifier: Build_poc_1769525801995
  projectIdentifier: appdemo
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Test
                  name: Test
                  identifier: Test
                  spec:
                    shell: Sh
                    command: |-
                      cd ./python-tests
                      pytest
                    intelligenceMode: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: poc
        build: <+input>
